server:
  port: 8081

ipcSocketPath: /home/root/.ethereum/geth.ipc

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://###:3306/###?useSSL=false
    username: root
    password: ###